# Generated by Django 3.1.3 on 2020-11-08 21:03

import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UnauthorizedUserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Name')),
                ('slug', models.SlugField(blank=True)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=content.models.image_folder, verbose_name='Image url')),
            ],
            options={
                'verbose_name': 'UnauthorizedUserLink',
                'verbose_name_plural': 'UnauthorizedUserLinks',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5, verbose_name='Версия')),
                ('description', models.TextField(verbose_name='Что нового в версии')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Текущий год')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Name')),
                ('slug', models.SlugField(blank=True)),
                ('link', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=content.models.image_folder, verbose_name='Image url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.category')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
